apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-app
        image: <your-dockerhub-username>/<image-name>:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
