# Frontend Dockerfile
FROM node:14 as build

# Set working directory
WORKDIR /app

# Copy project files
COPY package*.json /app/
RUN npm install

COPY . /app
RUN npm run build

# Serve the app using Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]