name: CD Pipeline - Testing to Prod

on:
  push:
    branches:
      - staging

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MLPROJECT }}

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes-deployment.yml

    - name: Push to Production Branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if git rev-parse --verify origin/prod >/dev/null 2>&1; then
          git checkout production
        else
          git checkout -b production
        fi
        git push https://${{ secrets.MLPROJECT }}@github.com/Hamza3087/Mlops_Project.git production

