name: CI/CD Pipeline - Dev to Prod

permissions:
  contents: write
  security-events: write  # Required for CodeQL to upload results

on:
  push:
    branches:
      - dev
      - staging

jobs:
  # CI Job: Test, Build, and Push to Staging
  test-build-deploy:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MLPROJECT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # - name: Install dependencies
    #   run: |
    #     pip install -r requirements.txt
    #     pip install pytest

    # - name: Run Unit Tests
    #   run: pytest tests/test_main.py

    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and Push Backend Docker Image
    #   run: |
    #     docker build -t hamza0707/mbackend:latest -f Dockerfile .
    #     docker push hamza0707/mbackend:latest

    # - name: Build and Push Frontend Docker Image
    #   run: |
    #     docker build -t hamza0707/mfrontend:latest -f my-app/Dockerfile my-app/
    #     docker push hamza0707/mfrontend:latest

    - name: Push to Staging Branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git checkout staging || git checkout -b staging
        git push origin staging

  # CD Job: Deploy to Production
  deploy-to-prod:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MLPROJECT }}

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes-deployment.yml

    - name: Push to Production Branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout production || git checkout -b production
        git push https://${{ secrets.MLPROJECT }}@github.com/Hamza3087/Mlops_Project.git production
