name: CD Pipeline - Production Deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy-to-prod:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Production Kubernetes
      run: |
        kubectl apply -f kubernetes-deployment.yml
        kubectl rollout status deployment/mlops-app
